### ISSUE TITLE
AmazonEchoControl Warning in openhab.log

### ISSUE THREAD

**Issue by BigGeorgeTx** [smarthomej/addons#245]
Everything seems to be working for me, but I noticed the following my log and I thought I would share it.  I hope this is the right place to do so.

I am running openHAB 3.2.0M5 on a Pi4B running openHABian.  I dropped the Smarthome/J 3.2.5 SNAPSHOT amazonechocontrol and common bindings into the addons folder, and they seem to work.  But I see this occasionally:

`2021-12-13 16:27:22.474 [WARN ] [mazonechocontrol.internal.Connection] - Request to url 'https://alexa.amazon.com/api/notification/sounds?deviceSerialNumber=G090RF04850606GC&deviceType=A7WXQPH584YP&softwareVersion=672720620' fails with unknown error
java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
	at java.net.Socket.connect(Socket.java:609) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[?:?]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:182) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?]
	at org.smarthomej.binding.amazonechocontrol.internal.Connection.makeRequest(Connection.java:641) ~[?:?]
	at org.smarthomej.binding.amazonechocontrol.internal.Connection.makeRequestAndReturnString(Connection.java:557) ~[?:?]
	at org.smarthomej.binding.amazonechocontrol.internal.Connection.makeRequestAndReturnString(Connection.java:552) ~[?:?]
	at org.smarthomej.binding.amazonechocontrol.internal.Connection.getNotificationSounds(Connection.java:1925) ~[?:?]
	at org.smarthomej.binding.amazonechocontrol.internal.handler.AccountHandler.refreshData(AccountHandler.java:547) ~[?:?]
	at org.smarthomej.binding.amazonechocontrol.internal.handler.AccountHandler.checkData(AccountHandler.java:460) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
`

**Comment by J-N-K** [comment]
Perfectly fine here. How often do you see these messages? "Connection time out" looks more like a network issue, could it be your internet connection is flaky?

**Comment by BigGeorgeTx** [comment]
I looked in my log and there were 4 in the last two days.

I have AT&T uverse 1GB fiber service, and our connection is generally quite stable and strong.

As I said, everything seems to be working, so I won't worry about it.  Just want to share what I found in the logs.

**Comment by J-N-K** [comment]
Error handling/reporting has been improved in latest version, exceptions are usually not logged to the user. If this happens again, please re-open.
