### ISSUE TITLE
Tuya Binding Illegal Argument Exception

### ISSUE THREAD

**Issue by BigGeorgeTx** [smarthomej/addons#332]
I upgraded my other system to openHAB3.3M1.  As part of the migration, as instructed, I first removed the Smarthome/J bindings that I use (Amazonechocontrol and Tuya).  When I reloaded the Tuya binding, I see the following (repeated very regularly) in the log.  There are 4 devices that are impacted, all smart light bulbs.  I can stop the error messages by disabling the Things.  This happens with both the production and the development versions of the binding.

Here is a TRACE level log
`2022-02-24 16:15:14.098 [TRACE] [.internal.local.handlers.TuyaDecoder] - udpListener: Received encoded '000055AA0000000000000013000000AC000000006836C27D6FF22C9527E586ABB979741064CC75D078B5F0CC244B0D54D470559B8DA5E6CB0FC3A1F11CB8790AC162611F18CA0C1BABD743880B08C3CD80E660C65FB9D6387160D3E4636F8EC084AAF888F462949A474596B425BAB23BABE68074E3C949D359D5C3EA6CD5201D408904BF7117BEF96ABD7BCCE4E49FD3A9BB51A1343378FD637A924CA2F95EAB619C9C2E2DD3A795424F2879A4492A51A7D90F07D43A6B810000AA55'
2022-02-24 16:15:14.100 [TRACE] [.internal.local.handlers.TuyaDecoder] - udpListener/: Decoded raw payload: {"ip":"10.0.0.227","gwId":"83425554bcddc268d218","active":2,"ability":0,"mode":0,"encrypt":true,"productKey":"key4fv3xs8twchhy","version":"3.3"}
2022-02-24 16:15:14.102 [DEBUG] [.internal.local.handlers.TuyaDecoder] - udpListener/: Received MessageWrapper{commandType=UDP_NEW, content='DiscoveryMessage{ip='10.0.0.227', deviceId='83425554bcddc268d218', active=2, ability=0, mode=0, encrypt=true, productKey='key4fv3xs8twchhy', version='3.3'}'}
2022-02-24 16:15:14.140 [DEBUG] [.internal.local.handlers.TuyaEncoder] - 83425554bcddc268d218/10.0.0.227:6668: Sending DP_QUERY, payload {devId=83425554bcddc268d218, uid=83425554bcddc268d218, t=1645744514, dps=null, gwId=83425554bcddc268d218}
2022-02-24 16:15:14.142 [TRACE] [.internal.local.handlers.TuyaEncoder] - 83425554bcddc268d218/10.0.0.227:6668: Sending encoded '000055AA000000010000000A000000885C9D15E783D537D6CEEB50EDD56B4EF3378F1D5E3778071AA9440EB88908856960C5AA71368D757CC64E7697A3DA0FE0D37699CC5C465EB80316B87A5900910D8ACBD9B6CE859C1D0D2D0965927558E3792FF8FC721F591A93DB8E42FF640C79C41E338A06381BAA0E556012D7F2547C7791FE3CB8ABD01DAB951F1FD69A993DB8D984A90000AA55'
2022-02-24 16:15:14.144 [DEBUG] [al.local.handlers.TuyaMessageHandler] - 83425554bcddc268d218/10.0.0.227:6668: Connection established.
2022-02-24 16:15:14.165 [TRACE] [.internal.local.handlers.TuyaDecoder] - 83425554bcddc268d218/10.0.0.227:6668: Received encoded '000055AA000000010000000A0000011C000000005C9D15E783D537D6CEEB50EDD56B4EF3378F1D5E3778071AA9440EB889088569D46E9F44464BAAB7CE53D1E3282452C9A01256A2074CE63F2798C1BDEA3D9264B2817B93D3C198ADAABDD367A8496A6AC50D82243B26F6975D3B7E44907D63E5A40A96561185004F8730676D1A1F1868CE3C796BAB4327DBFC8A811553A9C95A5902EFECDFCA3D12B8CB7A1A5DAF6A682A3AFD355E259911EA540EB5EB498BFC65019B819AB91E5C5471FE67BDD0ABF95643DDDEFF7C24ADC5978150AD58270933939F8AF53B3CF96BFBD75E49FF961A0645E42C751C6C784C7CCF2591EED770418674F2F3F5615F5A48181CB65A2F52CC3DB7758D7317A9BCFF7166DD9AF04D999EE3D2957CADB8080F8D73B67D02CC507B08AB0000AA55'
2022-02-24 16:15:14.167 [TRACE] [.internal.local.handlers.TuyaDecoder] - 83425554bcddc268d218//10.0.0.227:6668: Decoded raw payload: {"devId":"83425554bcddc268d218","dps":{"1":true,"2":"colour","3":139,"4":56,"5":"00008000f0ff8b","6":"bd76000168ffff","7":"ffff500100ff00","8":"ffff8003ff000000ff000000ff000000000000000000","9":"ffff5001ff0000","10":"ffff0505ff000000ff00ffff00ff00ff0000ff000000"}}
2022-02-24 16:15:14.169 [DEBUG] [.internal.local.handlers.TuyaDecoder] - 83425554bcddc268d218//10.0.0.227:6668: Received MessageWrapper{commandType=DP_QUERY, content='{1=true, 2=colour, 3=139.0, 4=56.0, 5=00008000f0ff8b, 6=bd76000168ffff, 7=ffff500100ff00, 8=ffff8003ff000000ff000000ff000000000000000000, 9=ffff5001ff0000, 10=ffff0505ff000000ff00ffff00ff00ff0000ff000000}'}
2022-02-24 16:15:14.170 [TRACE] [a.internal.handler.TuyaDeviceHandler] - 'tuya:tuyaDevice:83425554bcddc268d218' received status message '{1=true, 2=colour, 3=139.0, 4=56.0, 5=00008000f0ff8b, 6=bd76000168ffff, 7=ffff500100ff00, 8=ffff8003ff000000ff000000ff000000000000000000, 9=ffff5001ff0000, 10=ffff0505ff000000ff00ffff00ff00ff0000ff000000}'
2022-02-24 16:15:14.182 [WARN ] [rnal.local.handlers.UserEventHandler] - 83425554bcddc268d218/10.0.0.227:6668: class java.lang.IllegalArgumentException caught, closing the channel
java.lang.IllegalArgumentException: Value must be between 0 and 100
	at org.openhab.core.library.types.PercentType.validateValue(PercentType.java:93) ~[?:?]
	at org.openhab.core.library.types.PercentType.<init>(PercentType.java:88) ~[?:?]
	at org.smarthomej.binding.tuya.internal.util.ConversionUtil.hexColorDecode(ConversionUtil.java:48) ~[?:?]
	at org.smarthomej.binding.tuya.internal.handler.TuyaDeviceHandler.lambda$2(TuyaDeviceHandler.java:137) ~[?:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at org.smarthomej.binding.tuya.internal.handler.TuyaDeviceHandler.processDeviceStatus(TuyaDeviceHandler.java:123) ~[?:?]
	at org.smarthomej.binding.tuya.internal.local.handlers.TuyaMessageHandler.channelRead(TuyaMessageHandler.java:68) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [bundleFile:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [bundleFile:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [bundleFile:4.1.72.Final]
	at org.smarthomej.binding.tuya.internal.local.handlers.HeartbeatHandler.channelRead(HeartbeatHandler.java:90) [bundleFile:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [bundleFile:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [bundleFile:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [bundleFile:4.1.72.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [bundleFile:4.1.72.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [bundleFile:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [bundleFile:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [bundleFile:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [bundleFile:4.1.72.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [bundleFile:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [bundleFile:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [bundleFile:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [bundleFile:4.1.72.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [bundleFile:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [bundleFile:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [bundleFile:4.1.72.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [bundleFile:4.1.72.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [bundleFile:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [bundleFile:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [bundleFile:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [bundleFile:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [bundleFile:4.1.72.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [bundleFile:4.1.72.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [bundleFile:4.1.72.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [bundleFile:4.1.72.Final]
	at java.lang.Thread.run(Unknown Source) [?:?]
2022-02-24 16:15:14.207 [DEBUG] [al.local.handlers.TuyaMessageHandler] - 83425554bcddc268d218/10.0.0.227:6668: Connection terminated.
2022-02-24 16:15:14.491 [TRACE] [.internal.local.handlers.TuyaDecoder] - udpListener: Received encoded '000055AA00000000000000130000009C000000009E48FD861BAE64CD0E7538CF529ADD87F9F485FA79A3F289F80A8548E409BBA95D3601DE06AA476780AD532E849DD34D77BB6C9BCD33ED4F591FF9114B283767A483BE81E77F2E71F4307BD81685095E7E6FD47351A96972BDC91A04690E1EE139748132FE628885EED0E7AD9054446E03A041A1CB4D19ADA50F5E78DFF432964B95AC1F0A68B021B552634BAF99A3C50DF8D4680000AA55'
`

**Comment by J-N-K** [comment]
Can you show the the thing configuration?

**Comment by BigGeorgeTx** [comment]
Sure:

`UID: tuya:tuyaDevice:83425554bcddc268d218
label: Smart Bulb 6 (Tuya)
thingTypeUID: tuya:tuyaDevice
configuration:
  protocol: "3.3"
  productId: fnxgcsysunpyxkou
  deviceId: 83425554bcddc268d218
  ip: 10.0.0.227
  localKey: 07c7e1a1e453ad56
channels:
  - id: scene_data
    channelTypeUID: tuya:string
    label: scene_data
    description: null
    configuration:
      dp: 6
  - id: flash_scene_4
    channelTypeUID: tuya:string
    label: flash_scene_4
    description: null
    configuration:
      dp: 10
  - id: flash_scene_3
    channelTypeUID: tuya:string
    label: flash_scene_3
    description: null
    configuration:
      dp: 9
  - id: flash_scene_2
    channelTypeUID: tuya:string
    label: flash_scene_2
    description: null
    configuration:
      dp: 8
  - id: colour_data
    channelTypeUID: tuya:color
    label: colour_data
    description: null
    configuration:
      dp: 5
      dp2: 1
  - id: flash_scene_1
    channelTypeUID: tuya:string
    label: flash_scene_1
    description: null
    configuration:
      dp: 7
  - id: bright_value
    channelTypeUID: tuya:dimmer
    label: bright_value
    description: null
    configuration:
      min: 25
      dp: 3
      max: 255
      dp2: 1
  - id: temp_value
    channelTypeUID: tuya:dimmer
    label: temp_value
    description: null
    configuration:
      dp: 4
      max: 255
      min: 0
  - id: work_mode
    channelTypeUID: tuya:string
    label: work_mode
    description: null
    configuration:
      dp: 2
      range: white,colour,scene,scene_1,scene_2,scene_3,scene_4
`

**Comment by BigGeorgeTx** [comment]
Thanks.  Will you update the development binding, or should I download it from somewhere else to test it?

**Comment by J-N-K** [comment]
Yes, it's fixed in develop.

**Comment by BigGeorgeTx** [comment]
I removed and reinstalled the Tuya develop binding.  I'm seeing the following.  Also, I find that when I remove and reinstall the Tuya binding, the amazonechocontrol binding stops working and the Tuya binding doesn't work until I restart openHAB.

Here is the TRACE log filtered by the device ID:
`
2022-02-26 13:01:40.521 [WARN ] [rnal.local.handlers.UserEventHandler] - 83425554bcddc268d218/10.0.0.227:6668: class java.lang.IllegalArgumentException caught, closing the channel
2022-02-26 13:01:40.542 [DEBUG] [al.local.handlers.TuyaMessageHandler] - 83425554bcddc268d218/10.0.0.227:6668: Connection terminated.
2022-02-26 13:01:40.459 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tuya:tuyaDevice:83425554bcddc268d218' changed from OFFLINE to ONLINE
2022-02-26 13:01:40.546 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tuya:tuyaDevice:83425554bcddc268d218' changed from ONLINE to OFFLINE
2022-02-26 13:01:44.678 [TRACE] [.internal.local.handlers.TuyaDecoder] - udpListener/: Decoded raw payload: {"ip":"10.0.0.227","gwId":"83425554bcddc268d218","active":2,"ability":0,"mode":0,"encrypt":true,"productKey":"key4fv3xs8twchhy","version":"3.3"}
2022-02-26 13:01:44.680 [DEBUG] [.internal.local.handlers.TuyaDecoder] - udpListener/: Received MessageWrapper{commandType=UDP_NEW, content='DiscoveryMessage{ip='10.0.0.227', deviceId='83425554bcddc268d218', active=2, ability=0, mode=0, encrypt=true, productKey='key4fv3xs8twchhy', version='3.3'}'}
2022-02-26 13:01:45.569 [DEBUG] [.internal.local.handlers.TuyaEncoder] - 83425554bcddc268d218/10.0.0.227:6668: Sending DP_QUERY, payload {devId=83425554bcddc268d218, uid=83425554bcddc268d218, t=1645905705, dps=null, gwId=83425554bcddc268d218}
2022-02-26 13:01:45.570 [TRACE] [.internal.local.handlers.TuyaEncoder] - 83425554bcddc268d218/10.0.0.227:6668: Sending encoded '000055AA000000010000000A000000885C9D15E783D537D6CEEB50EDD56B4EF3378F1D5E3778071AA9440EB88908856960C5AA71368D757CC64E7697A3DA0FE0D37699CC5C465EB80316B87A5900910D1AEC9E14E7EFF96632FC9A06B02386E2792FF8FC721F591A93DB8E42FF640C79C41E338A06381BAA0E556012D7F2547C7791FE3CB8ABD01DAB951F1FD69A993D90367AD00000AA55'
2022-02-26 13:01:45.571 [DEBUG] [al.local.handlers.TuyaMessageHandler] - 83425554bcddc268d218/10.0.0.227:6668: Connection established.
2022-02-26 13:01:45.618 [TRACE] [.internal.local.handlers.TuyaDecoder] - 83425554bcddc268d218/10.0.0.227:6668: Received encoded '000055AA000000010000000A0000011C000000005C9D15E783D537D6CEEB50EDD56B4EF3378F1D5E3778071AA9440EB889088569D46E9F44464BAAB7CE53D1E3282452C9A01256A2074CE63F2798C1BDEA3D9264B2817B93D3C198ADAABDD367A8496A6AC50D82243B26F6975D3B7E44907D63E5A40A96561185004F8730676D1A1F1868CE3C796BAB4327DBFC8A811553A9C95A5902EFECDFCA3D12B8CB7A1A5DAF6A682A3AFD355E259911EA540EB5EB498BFC65019B819AB91E5C5471FE67BDD0ABF95643DDDEFF7C24ADC5978150AD58270933939F8AF53B3CF96BFBD75E49FF961A0645E42C751C6C784C7CCF2591EED770418674F2F3F5615F5A48181CB65A2F52CC3DB7758D7317A9BCFF7166DD9AF04D999EE3D2957CADB8080F8D73B67D02CC507B08AB0000AA55'
2022-02-26 13:01:45.619 [TRACE] [.internal.local.handlers.TuyaDecoder] - 83425554bcddc268d218//10.0.0.227:6668: Decoded raw payload: {"devId":"83425554bcddc268d218","dps":{"1":true,"2":"colour","3":139,"4":56,"5":"00008000f0ff8b","6":"bd76000168ffff","7":"ffff500100ff00","8":"ffff8003ff000000ff000000ff000000000000000000","9":"ffff5001ff0000","10":"ffff0505ff000000ff00ffff00ff00ff0000ff000000"}}
2022-02-26 13:01:45.573 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tuya:tuyaDevice:83425554bcddc268d218' changed from OFFLINE to ONLINE
2022-02-26 13:01:45.622 [DEBUG] [.internal.local.handlers.TuyaDecoder] - 83425554bcddc268d218//10.0.0.227:6668: Received MessageWrapper{commandType=DP_QUERY, content='{1=true, 2=colour, 3=139.0, 4=56.0, 5=00008000f0ff8b, 6=bd76000168ffff, 7=ffff500100ff00, 8=ffff8003ff000000ff000000ff000000000000000000, 9=ffff5001ff0000, 10=ffff0505ff000000ff00ffff00ff00ff0000ff000000}'}
2022-02-26 13:01:45.623 [TRACE] [a.internal.handler.TuyaDeviceHandler] - 'tuya:tuyaDevice:83425554bcddc268d218' received status message '{1=true, 2=colour, 3=139.0, 4=56.0, 5=00008000f0ff8b, 6=bd76000168ffff, 7=ffff500100ff00, 8=ffff8003ff000000ff000000ff000000000000000000, 9=ffff5001ff0000, 10=ffff0505ff000000ff00ffff00ff00ff0000ff000000}'
2022-02-26 13:01:45.627 [WARN ] [rnal.local.handlers.UserEventHandler] - 83425554bcddc268d218/10.0.0.227:6668: class java.lang.IllegalArgumentException caught, closing the channel
2022-02-26 13:01:45.639 [DEBUG] [al.local.handlers.TuyaMessageHandler] - 83425554bcddc268d218/10.0.0.227:6668: Connection terminated.
2022-02-26 13:01:45.642 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tuya:tuyaDevice:83425554bcddc268d218' changed from ONLINE to OFFLINE
2022-02-26 13:01:49.670 [TRACE] [.internal.local.handlers.TuyaDecoder] - udpListener/: Decoded raw payload: {"ip":"10.0.0.227","gwId":"83425554bcddc268d218","active":2,"ability":0,"mode":0,"encrypt":true,"productKey":"key4fv3xs8twchhy","version":"3.3"}
2022-02-26 13:01:49.671 [DEBUG] [.internal.local.handlers.TuyaDecoder] - udpListener/: Received MessageWrapper{commandType=UDP_NEW, content='DiscoveryMessage{ip='10.0.0.227', deviceId='83425554bcddc268d218', active=2, ability=0, mode=0, encrypt=true, productKey='key4fv3xs8twchhy', version='3.3'}'}
2022-02-26 13:01:50.660 [DEBUG] [.internal.local.handlers.TuyaEncoder] - 83425554bcddc268d218/10.0.0.227:6668: Sending DP_QUERY, payload {devId=83425554bcddc268d218, uid=83425554bcddc268d218, t=1645905710, dps=null, gwId=83425554bcddc268d218}
2022-02-26 13:01:50.663 [TRACE] [.internal.local.handlers.TuyaEncoder] - 83425554bcddc268d218/10.0.0.227:6668: Sending encoded '000055AA000000010000000A000000885C9D15E783D537D6CEEB50EDD56B4EF3378F1D5E3778071AA9440EB88908856960C5AA71368D757CC64E7697A3DA0FE0D37699CC5C465EB80316B87A5900910D0C9FA82B60E79854B5DBF4CBED298608792FF8FC721F591A93DB8E42FF640C79C41E338A06381BAA0E556012D7F2547C7791FE3CB8ABD01DAB951F1FD69A993D78C9C26E0000AA55'
2022-02-26 13:01:50.665 [DEBUG] [al.local.handlers.TuyaMessageHandler] - 83425554bcddc268d218/10.0.0.227:6668: Connection established.
2022-02-26 13:01:50.712 [TRACE] [.internal.local.handlers.TuyaDecoder] - 83425554bcddc268d218/10.0.0.227:6668: Received encoded '000055AA000000010000000A0000011C000000005C9D15E783D537D6CEEB50EDD56B4EF3378F1D5E3778071AA9440EB889088569D46E9F44464BAAB7CE53D1E3282452C9A01256A2074CE63F2798C1BDEA3D9264B2817B93D3C198ADAABDD367A8496A6AC50D82243B26F6975D3B7E44907D63E5A40A96561185004F8730676D1A1F1868CE3C796BAB4327DBFC8A811553A9C95A5902EFECDFCA3D12B8CB7A1A5DAF6A682A3AFD355E259911EA540EB5EB498BFC65019B819AB91E5C5471FE67BDD0ABF95643DDDEFF7C24ADC5978150AD58270933939F8AF53B3CF96BFBD75E49FF961A0645E42C751C6C784C7CCF2591EED770418674F2F3F5615F5A48181CB65A2F52CC3DB7758D7317A9BCFF7166DD9AF04D999EE3D2957CADB8080F8D73B67D02CC507B08AB0000AA55'
2022-02-26 13:01:50.714 [TRACE] [.internal.local.handlers.TuyaDecoder] - 83425554bcddc268d218//10.0.0.227:6668: Decoded raw payload: {"devId":"83425554bcddc268d218","dps":{"1":true,"2":"colour","3":139,"4":56,"5":"00008000f0ff8b","6":"bd76000168ffff","7":"ffff500100ff00","8":"ffff8003ff000000ff000000ff000000000000000000","9":"ffff5001ff0000","10":"ffff0505ff000000ff00ffff00ff00ff0000ff000000"}}
2022-02-26 13:01:50.716 [DEBUG] [.internal.local.handlers.TuyaDecoder] - 83425554bcddc268d218//10.0.0.227:6668: Received MessageWrapper{commandType=DP_QUERY, content='{1=true, 2=colour, 3=139.0, 4=56.0, 5=00008000f0ff8b, 6=bd76000168ffff, 7=ffff500100ff00, 8=ffff8003ff000000ff000000ff000000000000000000, 9=ffff5001ff0000, 10=ffff0505ff000000ff00ffff00ff00ff0000ff000000}'}
2022-02-26 13:01:50.718 [TRACE] [a.internal.handler.TuyaDeviceHandler] - 'tuya:tuyaDevice:83425554bcddc268d218' received status message '{1=true, 2=colour, 3=139.0, 4=56.0, 5=00008000f0ff8b, 6=bd76000168ffff, 7=ffff500100ff00, 8=ffff8003ff000000ff000000ff000000000000000000, 9=ffff5001ff0000, 10=ffff0505ff000000ff00ffff00ff00ff0000ff000000}'
2022-02-26 13:01:50.725 [WARN ] [rnal.local.handlers.UserEventHandler] - 83425554bcddc268d218/10.0.0.227:6668: class java.lang.IllegalArgumentException caught, closing the channel
2022-02-26 13:01:50.742 [DEBUG] [al.local.handlers.TuyaMessageHandler] - 83425554bcddc268d218/10.0.0.227:6668: Connection terminated.
2022-02-26 13:01:50.669 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tuya:tuyaDevice:83425554bcddc268d218' changed from OFFLINE to ONLINE
2022-02-26 13:01:50.744 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tuya:tuyaDevice:83425554bcddc268d218' changed from ONLINE to OFFLINE`

**Comment by J-N-K** [comment]
It seems that the assumption that the difference is 3.1/3.3 is wrong. I overlooked that this is a 3.3 device (since we were talking about 3.1 devices before). I'll check what I can do.

**Comment by J-N-K** [comment]
Can update again?

**Comment by BigGeorgeTx** [comment]
I just updating the Tuya develop binding.  I then enabled the 4 devices that weren't working before, and they all came on line.  I will check out functionality and report back, but there are no errors in the log at this point.  Thanks.

**Comment by BigGeorgeTx** [comment]
After 12 hours, everything is staying online, so it looks like this issue has been resolved.  Thanks.
