### ISSUE TITLE
[amazonechocontrol] DecimalType error

### ISSUE THREAD

**Issue by jimtng** [smarthomej/addons#333]
Another victim of https://github.com/openhab/openhab-core/pull/2596

```
java.lang.NoSuchMethodError: 'void org.openhab.core.library.types.DecimalType.<init>(long)'
        at org.smarthomej.binding.amazonechocontrol.internal.handler.EchoHandler.updateEqualizerState(EchoHandler.java:1191) ~[?:?]
        at org.smarthomej.binding.amazonechocontrol.internal.handler.EchoHandler.updateState(EchoHandler.java:885) ~[?:?]
        at org.smarthomej.binding.amazonechocontrol.internal.handler.AccountHandler.refreshData(AccountHandler.java:586) ~[?:?]
        at org.smarthomej.binding.amazonechocontrol.internal.handler.AccountHandler.checkData(AccountHandler.java:472) ~[?:?]
        at org.smarthomej.binding.amazonechocontrol.internal.handler.AccountHandler.setConnection(AccountHandler.java:429) ~[?:?]
        at org.smarthomej.binding.amazonechocontrol.internal.handler.AccountHandler.checkLogin(AccountHandler.java:393) ~[?:?]
```

**Comment by J-N-K** [comment]
Please check if after merging the fix in openHAB core (with tomorrows snapshot) there is still something we need to take care of.

**Comment by J-N-K** [comment]
Is this still an issue?

**Comment by jimtng** [comment]
I haven't seen the errors in the log since updating the snapshot.
