### ISSUE TITLE
Can't build tuya for OH 4.0.x

### ISSUE THREAD

**Issue by d51x** [smarthomej/addons#500]
Build success but when put kar-file into addons get error

`
16:16:01.014 [WARN ] [org.apache.felix.fileinstall         ] - Error while starting bundle: file:/usr/share/openhab/addons/org.smarthomej.binding.tuya-4.0.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.smarthomej.binding.tuya [361]
  Unresolved requirement: Import-Package: org.jose4j.base64url; version="[0.9.0,1.0.0)"

        at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) ~[?:?]
`

**Comment by d51x** [comment]
not works under OH 4.0.0-M3

works under OH 4.0.0-M4
