### ISSUE TITLE
Adding json to JSON 3rd party addon results in stacktrace for openHAB 4.1.1

### ISSUE THREAD

**Issue by pverhoye** [smarthomej/addons#558]
Following the documentation and adding https://download.smarthomej.org/addons.json as JSON 3rd Party Addon Service in the settings results in the new Add store page to keep loading.
In the logs I see first:
```
2024-01-12 12:14:46.774 [ERROR] [place.internal.json.JsonAddonService] - bundle org.openhab.core.addon.marketplace:4.1.1 (156)[org.openhab.core.addon.marketplace.internal.json.JsonAddonService(50)] : The modified method has thrown an exception
java.lang.IllegalArgumentException: Input does not match pattern
at org.openhab.core.addon.marketplace.BundleVersion.<init>(BundleVersion.java:63) ~[?:?]
	at org.openhab.core.addon.marketplace.AbstractRemoteAddonService.lambda$1(AbstractRemoteAddonService.java:68) ~[?:?]
	at java.util.TimSort.binarySort(TimSort.java:296) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:221) ~[?:?]
```

And later:

```
2024-01-12 12:16:14.948 [ERROR] [internal.JSONResponseExceptionMapper] - Unexpected exception occurred while processing REST request.
java.lang.IllegalArgumentException: Input does not match pattern
	at org.openhab.core.addon.marketplace.BundleVersion.<init>(BundleVersion.java:63) ~[?:?]
	at org.openhab.core.addon.marketplace.AbstractRemoteAddonService.lambda$1(AbstractRemoteAddonService.java:68) ~[?:?]
	at java.util.TimSort.binarySort(TimSort.java:296) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:221) ~[?:?]
```

**Comment by J-N-K** [comment]
Fixed by https://github.com/openhab/openhab-core/pull/4043, but I already added a server-side fix for now.
